language: scala

scala:
  - 2.10.6
  - 2.11.8

jdk:
  - oraclejdk6

matrix:
  include:
  - scala: 2.12.0
    jdk: oraclejdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.sbt/0.13/dependency
    - $HOME/.sbt/boot/scala*
    - $HOME/.sbt/launchers
    - $HOME/.ivy2/cache

sudo: false
